/** A subject entry in the curriculum */
export interface SubjectInfo {
  slug: string; // URL directory slug e.g. "arithmetic"
  label: string; // Display name e.g. "Arithmetic"
  aboutPath: string; // Link target e.g. "/arithmetic/about-arithmetic/"
  lessons: string[]; // Array of lesson slugs belonging to this subject
}

/** All 12 subjects in curriculum order, with their lesson slugs */
export const SUBJECTS: SubjectInfo[] = [
  {
    slug: "arithmetic",
    label: "Arithmetic",
    aboutPath: "/arithmetic/about-arithmetic/",
    lessons: [
      "about-arithmetic",
      "adding-fractions",
      "adding-subtracting-decimals",
      "addition-and-subtraction-single-digits",
      "addition-and-subtraction",
      "arithmetic-review",
      "base-10-and-place-value",
      "comparing-and-ordering-numbers",
      "converting-percentages",
      "counting-and-whole-numbers",
      "decimals-place-value",
      "dividing-decimals",
      "dividing-fractions",
      "division-single-digits",
      "division",
      "finding-percent-of-number",
      "introduction-to-fractions",
      "multiplication-single-digits",
      "multiplication",
      "multiplying-decimals",
      "multiplying-fractions",
      "percent-increase-decrease",
      "place-value-and-rounding",
      "real-world-percent-problems",
      "rounding-decimals",
      "subtracting-fractions",
      "understanding-percentages",
      "what-are-numbers",
    ],
  },
  {
    slug: "pre-algebra",
    label: "Pre-Algebra",
    aboutPath: "/pre-algebra/about-pre-algebra/",
    lessons: [
      "about-pre-algebra",
      "absolute-value-equations",
      "algebraic-proportions-and-ratios",
      "basic-graphing-coordinate-plane",
      "combining-like-terms",
      "distributive-property",
      "equations-variables-both-sides",
      "evaluating-expressions",
      "exponents-and-powers",
      "integers-and-signed-numbers",
      "order-of-operations",
      "pre-algebra-review",
      "simple-inequalities",
      "solving-one-step-equations",
      "solving-two-step-equations",
      "variables-and-expressions",
      "word-problems-with-variables",
    ],
  },
  {
    slug: "algebra-basics",
    label: "Algebra Basics",
    aboutPath: "/algebra-basics/about-algebra-basics/",
    lessons: [
      "about-algebra-basics",
      "algebra-basics-review",
      "applications-of-systems",
      "factoring-basics",
      "graphing-linear-equations",
      "introduction-to-functions",
      "introduction-to-polynomials",
      "linear-functions-and-slope",
      "linear-inequalities-multi-step",
      "literal-equations-and-formulas",
      "point-slope-and-standard-form",
      "slope-intercept-form",
      "solving-multi-step-linear-equations",
      "standard-form-and-conversions",
      "systems-elimination-method",
      "systems-graphing-method",
      "systems-substitution-method",
    ],
  },
  {
    slug: "geometry",
    label: "Geometry",
    aboutPath: "/geometry/about-geometry/",
    lessons: [
      "about-geometry",
      "adjacent-and-vertical-angles",
      "angles-and-angle-measures",
      "arcs-and-central-angles",
      "area-and-circumference",
      "classifying-triangles",
      "complementary-and-supplementary-angles",
      "distance-and-midpoint-formulas",
      "geometry-review",
      "graphing-geometric-figures",
      "interior-and-exterior-angles-of-polygons",
      "line-segments-and-rays",
      "parallel-lines-and-transversals",
      "parts-of-a-circle",
      "perimeter-and-area-of-polygons",
      "points-lines-and-planes",
      "properties-of-quadrilaterals",
      "pythagorean-theorem",
      "slope-in-the-coordinate-plane",
      "triangle-sum-theorem",
    ],
  },
  {
    slug: "algebra-2",
    label: "Algebra 2",
    aboutPath: "/algebra-2/about-algebra-2/",
    lessons: [
      "about-algebra-2",
      "algebra-2-review",
      "arithmetic-sequences",
      "circles-and-parabolas",
      "complex-numbers-in-quadratic-equations",
      "discriminant-and-number-of-solutions",
      "domain-and-range",
      "ellipses-and-hyperbolas",
      "exponential-growth-and-decay",
      "factoring-higher-degree-polynomials",
      "function-notation-and-evaluation",
      "geometric-sequences",
      "graphing-quadratic-functions",
      "identifying-conic-sections",
      "introduction-to-complex-numbers",
      "introduction-to-conic-sections",
      "introduction-to-functions",
      "introduction-to-logarithms",
      "introduction-to-matrices",
      "introduction-to-polynomial-functions",
      "inverse-functions",
      "multiplying-dividing-rational-expressions",
      "nonlinear-systems",
      "operations-with-complex-numbers",
      "operations-with-radicals",
      "piecewise-functions",
      "polynomial-operations",
      "properties-of-logarithms",
      "rational-root-theorem",
      "simplifying-radicals-and-rational-exponents",
      "simplifying-rational-expressions",
      "solving-quadratic-equations",
      "solving-radical-equations",
      "solving-rational-equations",
      "solving-systems-using-matrices",
      "systems-with-three-variables",
      "vertex-form-and-transformations",
    ],
  },
  {
    slug: "trigonometry",
    label: "Trigonometry",
    aboutPath: "/trigonometry/about-trigonometry/",
    lessons: [
      "about-trigonometry",
      "applications-of-right-triangle-trig",
      "applications-of-trig-equations",
      "applications-triangle-solving",
      "basic-trig-equations",
      "equations-with-multiple-angles",
      "fundamental-identities",
      "graphing-sine-and-cosine",
      "graphing-tangent-and-reciprocal",
      "introduction-to-trigonometry",
      "law-of-cosines",
      "law-of-sines",
      "radians-and-degree-conversion",
      "solving-right-triangles",
      "sum-and-difference-identities",
      "the-unit-circle",
      "transformations-of-trig-graphs",
      "trig-functions-on-the-unit-circle",
      "trigonometry-review",
      "verifying-trig-identities",
    ],
  },
  {
    slug: "pre-calculus",
    label: "Pre-Calculus",
    aboutPath: "/pre-calculus/about-pre-calculus/",
    lessons: [
      "about-pre-calculus",
      "advanced-exponential-and-logarithmic-equations",
      "advanced-trigonometric-equations",
      "advanced-trigonometric-identities",
      "arithmetic-and-geometric-series",
      "complex-zeros-and-fundamental-theorem",
      "continuity-and-limit-laws",
      "determinants-and-cramers-rule",
      "function-composition-and-operations",
      "introduction-to-limits",
      "introduction-to-vectors",
      "inverse-functions",
      "mathematical-induction",
      "matrix-operations-and-inverses",
      "modeling-with-exponentials-and-logarithms",
      "natural-logarithms-and-applications",
      "piecewise-and-absolute-value-functions",
      "polar-coordinates-and-equations",
      "polynomial-graphs-and-end-behavior",
      "pre-calculus-review",
      "rational-functions-and-asymptotes",
      "solving-systems-with-matrices",
      "vector-operations-and-applications",
    ],
  },
  {
    slug: "calculus-1",
    label: "Calculus 1",
    aboutPath: "/calculus-1/about-calculus-1/",
    lessons: [
      "about-calculus-1",
      "antiderivatives-and-indefinite-integrals",
      "area-under-a-curve",
      "average-value-of-a-function",
      "basic-derivative-rules",
      "calculus-1-review",
      "chain-rule",
      "curve-sketching",
      "definite-integrals-and-fundamental-theorem",
      "derivatives-of-exponential-and-logarithmic-functions",
      "derivatives-of-trigonometric-functions",
      "implicit-differentiation",
      "integration-by-substitution",
      "introduction-to-derivatives",
      "limit-definition-of-the-derivative",
      "limits-and-continuity-review",
      "linear-approximations-and-differentials",
      "maxima-and-minima",
      "mean-value-theorem",
      "net-change-and-total-change",
      "optimization-problems",
      "product-and-quotient-rules",
      "related-rates",
    ],
  },
  {
    slug: "calculus-2",
    label: "Calculus 2",
    aboutPath: "/calculus-2/about-calculus-2/",
    lessons: [
      "about-calculus-2",
      "alternating-series-and-absolute-convergence",
      "applications-of-taylor-series",
      "arc-length-and-surface-area",
      "area-between-curves",
      "calculus-2-review",
      "convergence-tests",
      "improper-integrals",
      "integration-by-parts",
      "introduction-to-differential-equations",
      "linear-differential-equations",
      "partial-fractions",
      "physics-applications",
      "power-series",
      "review-of-basic-integration-and-substitution",
      "separable-differential-equations",
      "sequences-and-series-basics",
      "taylor-and-maclaurin-series",
      "trigonometric-integrals",
      "trigonometric-substitution",
      "volumes-by-disks-and-washers",
      "volumes-by-shells",
      "work-and-average-value",
    ],
  },
  {
    slug: "calculus-3",
    label: "Calculus 3",
    aboutPath: "/calculus-3/about-calculus-3/",
    lessons: [
      "about-calculus-3",
      "arc-length-and-curvature",
      "calculus-3-review",
      "chain-rule-for-multivariable-functions",
      "conservative-vector-fields",
      "curl-and-divergence",
      "directional-derivatives-and-the-gradient",
      "double-integrals-in-polar-coordinates",
      "double-integrals-over-general-regions",
      "double-integrals-over-rectangular-regions",
      "greens-theorem",
      "line-integrals",
      "partial-derivatives-and-the-gradient",
      "stokes-theorem",
      "surface-integrals",
      "tangent-planes-and-linear-approximations",
      "the-divergence-theorem",
      "triple-integrals-in-cylindrical-and-spherical-coordinates",
      "triple-integrals",
      "vector-fields",
      "vector-functions-and-space-curves",
      "vectors-and-geometry-in-3d-space",
    ],
  },
  {
    slug: "linear-algebra",
    label: "Linear Algebra",
    aboutPath: "/linear-algebra/about-linear-algebra/",
    lessons: [
      "about-linear-algebra",
      "applications-in-computer-graphics-and-games",
      "basis-and-dimension",
      "cross-product-and-vector-projections",
      "diagonalization",
      "eigenvalues-and-eigenvectors",
      "gaussian-elimination",
      "linear-algebra-review",
      "linear-transformations",
      "matrices-and-basic-matrix-operations",
      "matrix-inverses-and-determinants",
      "matrix-multiplication-and-transformations",
      "systems-of-linear-equations",
      "vector-operations",
      "vector-spaces-and-linear-independence",
      "vectors-in-2d-and-3d",
    ],
  },
  {
    slug: "differential-equations",
    label: "Differential Equations",
    aboutPath: "/differential-equations/about-differential-equations/",
    lessons: [
      "about-differential-equations",
      "applications-growth-and-decay",
      "applications-mixing-problems",
      "applications-newtons-law-of-cooling",
      "applications-spring-mass-systems",
      "complex-roots-and-oscillation",
      "differential-equations-review",
      "direction-fields-and-solution-curves",
      "exact-equations",
      "first-order-linear-equations",
      "laplace-transforms-definition-and-properties",
      "laplace-transforms-solving-ivps",
      "nonhomogeneous-equations-undetermined-coefficients",
      "numerical-methods-eulers-method",
      "phase-plane-analysis",
      "second-order-homogeneous-equations",
      "separable-equations",
      "systems-of-differential-equations",
      "variation-of-parameters",
      "what-is-a-differential-equation",
    ],
  },
  {
    slug: "discrete-mathematics",
    label: "Discrete Mathematics",
    aboutPath: "/discrete-mathematics/about-discrete-mathematics/",
    lessons: [
      "about-discrete-mathematics",
      "combinations",
      "conditional-statements-and-implications",
      "direct-proof-and-counterexample",
      "discrete-mathematics-review",
      "introduction-to-graph-theory",
      "introduction-to-sets",
      "logical-equivalence-and-de-morgans-laws",
      "modular-arithmetic",
      "paths-cycles-and-connectivity",
      "permutations",
      "predicates-and-quantifiers",
      "proof-by-contradiction-and-contrapositive",
      "proof-by-induction",
      "propositional-logic-and-truth-tables",
      "relations-and-functions",
      "set-operations-and-venn-diagrams",
      "the-counting-principles",
      "the-pigeonhole-principle",
      "trees-and-spanning-trees",
      "what-is-discrete-mathematics",
    ],
  },
  {
    slug: "statistics",
    label: "Statistics",
    aboutPath: "/statistics/about-statistics/",
    lessons: [
      "about-statistics",
      "bayes-theorem",
      "conditional-probability-and-independence",
      "confidence-intervals",
      "correlation-and-linear-regression",
      "displaying-data-with-charts",
      "five-number-summary-and-boxplots",
      "hypothesis-testing-basics",
      "introduction-to-probability",
      "measures-of-center",
      "measures-of-spread",
      "p-values-and-errors",
      "probability-rules",
      "random-variables-and-expected-value",
      "sampling-distributions-and-the-central-limit-theorem",
      "statistics-review",
      "the-binomial-distribution",
      "the-normal-distribution",
      "types-of-data-and-levels-of-measurement",
      "what-is-statistics",
      "z-scores-and-the-empirical-rule",
    ],
  },
];

/** Total number of lessons available across all subjects */
export const TOTAL_LESSONS: number = SUBJECTS.reduce(
  (sum, subject) => sum + subject.lessons.length,
  0,
);

/** Lookup: lesson slug → subject slug (for filtering unknown keys) */
export const SLUG_TO_SUBJECT: Map<string, string> = new Map(
  SUBJECTS.flatMap((subject) =>
    subject.lessons.map((lesson) => [lesson, subject.slug] as [string, string]),
  ),
);
